### ISSUE TITLE
Integrating Lightify plug in Hue system

### ISSUE THREAD

**Issue by Vuille** [Hyrules/WinHue3#66] opened 2017-02-10 14:25 UTC
I inserted a just unpacked OSRAM Lightify plug into a Hue system and searched for it. The Hue bridge did not detect it. I read different comments that it is necessary to reset it first. To do this, you need a Lightify gateway. I have one, but I could never bring it to work (setup failed). So finally the following procedure was successful: I simply inserted the plug in a wall socket for 3 seconds, removed it for another 3 seconds and did it over 4 more times (5 times altogether). That did reset the plug.
Afterwards, I searched for it on the Hue bridge API (with POST  "/api/<user ID>/lights") and got the new object (with GET "/api/\user ID>/lights/new"). I assume the same procedure applies on WinHue, which now shows that new object in the group of lights as "On/Off plug-in unit".
I had no problem inserting Lightify bulbs in the Hue system, they were detected straight forward without applying the reset procedure. If needed, I assume the procedure described here above would work as well.

**Comment by Hyrules** [comment] 2017-02-10 15:27
How does WinHue react to thos object ? Are you able to control them without error ?

**Comment by Vuille** [comment] 2017-02-10 18:06
The Lightify plug is just an on/off object. I use it to control a non-hue lighting device, like a fake TV. I should be able to include it in a rule to drive it. I will do it and let you know.
As far as the Lightify bulbs are concerned, they just behave like Hue lamps. I have two of them driven by rules which work fine.

**Comment by Vuille** [comment] 2017-02-10 21:49
I integrated the Lightify plug in a rule and in a schedule without any problem. However, I had to set up a schedule in the bridge API; creating a schedule in WinHue triggered an error (error 7 about time format).

**Comment by Vuille** [comment] 2017-02-11 09:37
It is not only impossible to create a schedule in WinHue, but also to edit an existing one. Whatever time you  enter, it triggers error 7 (wrong time format). Recent logs are attached.
[WinHue3 2017-02-10.txt](https://github.com/Hyrules/WinHue3/files/768315/WinHue3.2017-02-10.txt)
[WinHue3 2017-02-11.txt](https://github.com/Hyrules/WinHue3/files/768314/WinHue3.2017-02-11.txt)

**Comment by Hyrules** [comment] 2017-02-11 14:34
I know if this unfortunately it's because of a bug in the Xceed WPF toolkit. I will try to find a way to bypass it.

**Comment by Hyrules** [comment] 2017-02-15 23:58
This version should work properly.

[WinHue 3 BETA 26 Setup.zip](https://github.com/Hyrules/WinHue3/files/778704/WinHue.3.BETA.26.Setup.zip)

**Comment by Vuille** [comment] 2017-02-16 10:43
I have installed version BETA 26. Unfortunately, there is still error 7 (wrong time format) when editing schedules.

**Comment by Hyrules** [comment] 2017-02-16 11:41
hmm. most likely the localized time causing the error because I cannot reproduce it here. The date should be like this yyyy/mm/dd but yours is m/dd/yyyy. I will try to fix this.

**Comment by Vuille** [comment] 2017-02-16 13:27
You are right: in that version, date is displayed as dd/mm/yyyy. I will appreciate if you can fix it.

**Comment by Hyrules** [comment] 2017-02-16 21:25
Can you try this version and let me know what happens ?

[WinHue 3 BETA 26 Setup.zip](https://github.com/Hyrules/WinHue3/files/781578/WinHue.3.BETA.26.Setup.zip)

**Comment by Vuille** [comment] 2017-02-16 22:02
Same date format error when editing schedules. In the edit form, date displays as dd/mm/yyyy whereas it should be yyyy/mm/dd.

**Comment by Hyrules** [comment] 2017-02-16 22:12
This one ?

[WinHue 3 BETA 26 Setup.zip](https://github.com/Hyrules/WinHue3/files/781682/WinHue.3.BETA.26.Setup.zip)

**Comment by Vuille** [comment] 2017-02-16 22:36
The schedule edit form displays date as yyyy/mm/dd. But when I modify any value and click on the button save, the same error 7 about date/time format appears.
I noticed something else. If I install that new version without uninstalling the current one, I cannot launch the program ("An unexpected error has occurred...") If I first completely uninstall the current version 26, same problem. I have to uninstall version 26, then install version 25, then install on it the new version 26 to get it done.

**Comment by Hyrules** [comment] 2017-02-16 22:42
I would need a log with the unexcpected error do debug that. I will get you another version for the date string.

**Comment by Hyrules** [comment] 2017-02-16 23:01
Once more...

[WinHue 3 BETA 26 Setup.zip](https://github.com/Hyrules/WinHue3/files/781761/WinHue.3.BETA.26.Setup.zip)

**Comment by Vuille** [comment] 2017-02-17 08:35
Sorry not to have supplied you with a log, it was too late for me last night.
This morning, I installed the last version and made a couple of quick tests, Everything works fine as far as the time string while editing of schedules is concerned, Thank you.

**Comment by Vuille** [comment] 2017-02-17 08:40
Another issue about creating a schedule. Selecting type "Alarm" opens a form enabling the selection of the days of the week. After you have made your selection and you save it, an error message displays "...error 6, parameter, autodelete, not available at address..."

**Comment by Vuille** [comment] 2017-02-17 09:02
Strange... I cannot reproduce the error described in my last comment, about alarms>parameter:autodelete !
So please so far ignore it; other tests I did show this functions works fine.

**Comment by Hyrules** [comment] 2017-02-17 21:17
Autodelete should only be visible for non-recurring schedules. So this might be the cause of it. I will correct this.

**Comment by Hyrules** [comment] 2017-02-26 15:23
The problem with the exception should be fixed because of a missing DLL see issue #73 for download.

**Comment by Hyrules** [comment] 2018-03-05 20:24
if you still have issue please feel free to open a new issue otherwise i'm closing thins one.

**Closed by Hyrules** 2018-03-05 20:24 UTC
Labels: bug
