### ISSUE TITLE
Lights Do Not Show Specific Icons

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue3#105] opened 2017-08-25 21:10 UTC
This hasn't been an issue for me on all versions, but with RC1 and RC2, my installation shows the default A19 icon for all of my lights. The lamps labelled Bloom and Lightstrip are obviously some of the lights with the wrong icon. [Log ](https://pastebin.com/bLNUsJGN)if it helps (but no exception was generated).

![image](https://user-images.githubusercontent.com/30214760/29732679-9ab5c63a-89e1-11e7-88e3-f25e3cf78b74.png)

**Comment by Hyrules** [comment] 2017-08-25 22:58
from what I see in the log, the lights you have are simply not recognized by the lights already existing. This is not a bug per se. The lights images with the model does not exists in the light folder. If you want to fix this you can copy the lights in the lights folder of WinHue and rename them accordingly to the models you have.

**Comment by banksio** [comment] 2017-08-25 23:13
OK. I downloaded the latest source zip and copied the icons from there into my installation folder, which fixed the issue. Shouldn't the installer have done that though? Maybe it didn't modify that folder upon installation since I'd already had a previous installation of WH RC1?

**Comment by Hyrules** [comment] 2017-08-25 23:17
technically some of the lights are supposed to be in the Light folder of WinHue. Those are loaded at startup but other lights models which are not present uses the default image.

**Comment by banksio** [comment] 2017-08-25 23:24
My lights do show up now I've copied down the icons from the source zip, but the icons were not put there by the installer as they should've been, I don't think? (I haven't renamed any, just copied from latest release zip)

**Comment by Hyrules** [comment] 2017-08-25 23:26
can you try to uninstall the program and remove the folder if any and try to reinstall to see if there is indeed and issue with the installer ? Also after that can you try running the install as admin ? Just curious to see if permissions are causing this.

**Comment by banksio** [comment] 2017-08-25 23:43
After uninstalling for the first time, this was left over (the ones I copied manually from source zip):
![image](https://user-images.githubusercontent.com/30214760/29736169-d99e2cb0-89f6-11e7-8376-b37372e47777.png)

I then deleted the WinHue 3 folder completely and ran the installer again. The same problem occured as in the first comment in this thread (not all models are there):
![image](https://user-images.githubusercontent.com/30214760/29736226-3a4f68e4-89f7-11e7-94c1-d2b885d0aff1.png)

So it seems that the installer is not copying the latest `/lights/` directory that is in the source zip.

Also, the installer would not run at all without admin perms.

**Comment by Hyrules** [comment] 2017-08-25 23:47
ok i got it for some reason the lights where not configured to be copied to the bin folder of the compile app when compiling i have corrected that.

**Comment by Hyrules** [comment] 2017-08-25 23:51
Here you can try this version it should be fixed.

[WinHue 3 RC 3 Setup.zip](https://github.com/Hyrules/WinHue3/files/1253250/WinHue.3.RC.3.Setup.zip)

**Comment by banksio** [comment] 2017-08-25 23:54
Works like a charm. Thank you for your quick support!

**Comment by Hyrules** [comment] 2017-08-25 23:57
Not a problem. By the way don't try the RSSFeedMonitor it wont work.

**Comment by Hyrules** [comment] 2017-10-10 22:45
I'll close this since you fixed it in the next version. Thanks again !

**Closed by Hyrules** 2017-10-10 22:45 UTC
Labels: bug
