### ISSUE TITLE
Winhue won't control Hue Starter kit

### ISSUE THREAD

**Issue by AggieMikeATM** [Hyrules/WinHue3#101] opened 2017-07-31 14:14 UTC
Installed Winhue 3.
Bridge is detected and recognized.
Individual lights can be seen in Winhue.
Lights turn on when supplied power
No variables can be changed via software or detection blinking sequence activated.
In attributes recognition variable shows as "false"

I must be doing something wrong. Please advise.

Thank you for creating this software. I would just as soon not hand Phillips all my personal information through their app.

**Comment by Hyrules** [comment] 2017-07-31 14:29
are there any errors in the log ?

**Comment by AggieMikeATM** [comment] 2017-07-31 15:11
I don't see anything in the log that says "Error" a few "Debug"s and reachable "false"s. 

Screencap:
			

![winhue log1](https://user-images.githubusercontent.com/30583411/28784241-6d94b75a-75d8-11e7-9f18-df07ec68b9da.PNG)

**Comment by Hyrules** [comment] 2017-07-31 15:16
Can you send me the log file ? It's located in the %appdata%\WinHue\log folder i'll take a look to see if there is anything I can find.

**Comment by AggieMikeATM** [comment] 2017-07-31 15:48
Dell - Internal Use - Confidential
Sorry if I am being obtuse here but when I look in the AppData folder there is not Winhue folder or log file in Local or Roaming. I must be looking in wrong place.

[cid:image001.png@01D309EA.86161DF0]

Michael Spillers
Inside Sales Account Manager
Dell | U.S. Sales – Business Development
office +1 512-513-0094
Michael_Spillers@dell.com

How am I doing?  Please reach out to my Manager Alison_Ady@dell.com<mailto:Alison_Ady@dell.com> with any feedback.

**Comment by Hyrules** [comment] 2017-07-31 15:54
There should be in roaming. Normally the program stores your settings there as well and the logs.

**Comment by AggieMikeATM** [comment] 2017-07-31 16:10
Any idea where else it would be?

[cid:image001.png@01D309EB.FE70B480]

Michael Spillers
Inside Sales Account Manager
Dell | U.S. Sales – Business Development
office +1 512-513-0094
Michael_Spillers@dell.com

How am I doing?  Please reach out to my Manager Alison_Ady@dell.com<mailto:Alison_Ady@dell.com> with any feedback.

**Comment by Hyrules** [comment] 2017-07-31 16:18
You can try looking in the program files folder but i really doubt it's there since the saving settings get the environment variable for appdata : 
Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);

Do you have to pair the bridge every time you run the application ?

**Comment by AggieMikeATM** [comment] 2017-07-31 16:25
Dell - Internal Use - Confidential
Nope seems to see bridge fine. I have a dedicated IP there. I will dig some more and see what I can find.
Do you recommend I just reinstall?

Michael Spillers
Inside Sales Account Manager
Dell | U.S. Sales – Business Development
office +1 512-513-0094
Michael_Spillers@dell.com

How am I doing?  Please reach out to my Manager Alison_Ady@dell.com<mailto:Alison_Ady@dell.com> with any feedback.

**Comment by Hyrules** [comment] 2017-07-31 17:07
No reinstalling will not help.

**Comment by AggieMikeATM** [comment] 2017-07-31 18:49
Dell - Internal Use - Confidential
Is there a specific file name I should be searching for?

Michael Spillers
Inside Sales Account Manager
Dell | U.S. Sales – Business Development
office +1 512-513-0094
Michael_Spillers@dell.com

How am I doing?  Please reach out to my Manager Alison_Ady@dell.com<mailto:Alison_Ady@dell.com> with any feedback.

**Comment by Hyrules** [comment] 2017-07-31 18:55
if you find WinHueSettings.set you should be near the logs.

**Comment by AggieMikeATM** [comment] 2017-07-31 20:48
Found it. That helped. See attached.
Thank you

Michael Spillers
Inside Sales Account Manager
Dell | U.S. Sales – Business Development
office +1 512-513-0094
Michael_Spillers@dell.com

How am I doing?  Please reach out to my Manager Alison_Ady@dell.com<mailto:Alison_Ady@dell.com> with any feedback.

**Comment by Hyrules** [comment] 2017-07-31 21:03
Indeed the lights seems unreachable. That's most likely the reason you cannot control them with WinHue

You can try to use the clip debugger in the bridge to see what happens : 
go to that addresse : http://192.168.0.15/debug/clip.html

you will see a window where you can send commands to the bridge.

paste this command /api/5I8at3axpz3hSerjZzSb0LXxAwTKvMPtLHASyoiG/lights in the url and press get.

you should get a lights inside the bridge. Copy and paste the text here so I can see what happens to the light or at least tell me if there is something in the bridge or with WinHue.

**Comment by AggieMikeATM** [comment] 2017-07-31 23:15
Dell - Internal Use - Confidential
3 Blue lights and a blue ring on bridge.


{
    "1": {
        "state": {
            "on": true,
            "bri": 36,
            "alert": "select",
            "reachable": false
        },
        "type": "Dimmable light",
        "name": "which one",
        "modelid": "LWB014",
        "manufacturername": "Philips",
        "uniqueid": "00:17:88:01:02:29:9d:21-0b",
        "swversion": ""
    },
    "2": {
        "state": {
            "on": true,
            "bri": 186,
            "alert": "select",
            "reachable": false
        },
        "type": "Dimmable light",
        "name": "Hue white lamp 2",
        "modelid": "LWB014",
        "manufacturername": "Philips",
        "uniqueid": "00:17:88:01:02:29:9e:40-0b",
        "swversion": ""
    }


Michael Spillers
Inside Sales Account Manager
Dell | U.S. Sales – Business Development
office +1 512-513-0094
Michael_Spillers@dell.com

How am I doing?  Please reach out to my Manager Alison_Ady@dell.com<mailto:Alison_Ady@dell.com> with any feedback.

**Comment by Hyrules** [comment] 2017-07-31 23:18
Well the problem is not with WinHue. If the bridge detects them as unreachable it's because they most likely are unreachable in some way. Stupid question maybe but is the switch on the wall where they are plugged in on ? How far are they from the bridge. If the lights are too far they might be unreachable. Zigbee object like those lights relay the signal around. If they are too far they wont be able to relay the signal.

**Comment by AggieMikeATM** [comment] 2017-08-01 00:16
Dell - Internal Use - Confidential
One light is 5 feet from the bridge, in a lamp, turned on. The hub can see the bulbs but I cant change any of the variables in winhue. Is there a way I could try out winhue 2? Do you recommend me trying another bridge?


Michael Spillers
Inside Sales Account Manager
Dell | U.S. Sales – Business Development
office +1 512-513-0094
Michael_Spillers@dell.com

How am I doing?  Please reach out to my Manager Alison_Ady@dell.com<mailto:Alison_Ady@dell.com> with any feedback.

**Comment by Hyrules** [comment] 2017-08-01 00:22
WinHue 2 is not compatible with new version of the bridge and like I said the problem is not WinHue here. The problem is something else. The bridge state that reachable is false. If reachable is false WinHue won't let you change anything to prevent errors. If you try to modify anything with the clip debugger as well you will get some error messages stating that the object is not reachable. You could try deleting one light with WinHue and try to find it again using the search for new lights feature. Try unplugging the power on your bridge wait a little like a few minutes and plug it in again. See if that fixes the problem.

**Comment by Hyrules** [comment] 2017-08-11 18:15
Where you able to find the reason of the problem ?

**Comment by Hyrules** [comment] 2017-10-10 23:02
if you want to try the release in #108 and let me know if you still have this issue otherwill I will close it soon.

**Comment by AggieMikeATM** [comment] 2017-10-11 16:27
Thanks,

I’ll give it a try tonight

Michael Spillers
Inside Sales Account Manager
Dell | U.S. Sales – Business Development
office +1 512-513-0094
Michael_Spillers@dell.com

How am I doing?  Please reach out to my Manager Carolyn_Langley@Dell.com<mailto:Carolyn_Langley@Dell.com>  with any feedback.

**Comment by Hyrules** [comment] 2018-03-05 20:23
Do you still have this issue ? If so please feel free to reopen the issue otherwise i'm closing it.

**Closed by Hyrules** 2018-03-05 20:23 UTC

**Comment by AggieMikeATM** [comment] 2018-03-05 22:54
I don’t. Sorry for not following up. The issue was that the hub was just plumb broke. I ended up installing the app ( now Philips probably has stolen everything ) and it still didn’t work. I went back to home depot and exchanged it and the new hub worked like a champ.

Thanks you for checking back.

Michael Spillers
