### ISSUE TITLE
Rules with names longer than 20 characters not editable/updatable in Beta 25

### ISSUE THREAD

**Issue by Rocket78** [Hyrules/WinHue3#68] opened 2017-02-12 12:15 UTC
As the topic says. The "name" field of the rule is outlined red and "update" stays greyed out. Beta 24 worked well. (Had to downgrade because I wanted to insert the bridge's daylight sensor into the day rules because the motion sensor rests in a dark spot or too dark spot for its own sensor to measure correctly - even on the lowest level.)

**Comment by Hyrules** [comment] 2017-02-12 14:41
I will take a look at this.

**Comment by Hyrules** [comment] 2017-02-12 16:19
I cannot reproduce here. Can you give me the JSON of your rule ? Just right click in WinHue -> copy -> copy has json formatted and paste it here so I can see what is happening.

**Comment by xIngenuusx** [comment] 2017-02-12 16:51
I can reproduce this issue.
If the Name of the rule contains more then 20 characters the Border will be red and the update button is grayed out

**Comment by Rocket78** [comment] 2017-02-12 16:51
It is not "my" rule, it is the rule created by the hue (android) app while setting up the motion sensor:

{"name":"MotionSensor 12.day-on","conditions":[{"address":"/sensors/14/state/status","operator":"lt","value":"1"},{"address":"/config/localtime","operator":"in","value":"T07:00:00/T23:30:00"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/1/state/daylight","operator":"eq","value":"false"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"fpTMMyuPNkYFwER"}},{"address":"/sensors/14/state","method":"PUT","body":{"status":"1"}}],"owner":"OLUUFF6lIFS9Fjvua41ycrnMWO1UKXSCAgnR1Kf3","timestriggered":3,"lasttriggered":"2017-02-12T16:47:32","created":"2017-02-12T11:33:14","status":"enabled"}

**Comment by Hyrules** [comment] 2017-02-12 17:01
Hmm ok yes. I have set the rule name to be a max of 20 characters. I'm trying to find where in the Philips Hue API is the limit for names of rules because it's not unlimited...

**Comment by Hyrules** [comment] 2017-02-12 17:07
Here is an updated version. The max number of characters has been increased to 32. Like always the philips hue api is incomplete.

[WinHue 3 BETA 26 Setup.zip](https://github.com/Hyrules/WinHue3/files/769461/WinHue.3.BETA.26.Setup.zip)

**Comment by xIngenuusx** [comment] 2017-02-12 17:08
I think the max lenght is 33 Chars

**Comment by Hyrules** [comment] 2017-02-12 17:13
Groups, Lights and schedules are all 32 chars max so I assume the max length for the scenes is also 32.

**Comment by Hyrules** [comment] 2017-02-13 13:18
Anyone can tell me if this is fixed in the version posted ?

**Comment by xIngenuusx** [comment] 2017-02-13 14:17
Yes it s sccessfully fixed in the postet Version. Thanks

**Closed** 2017-02-25 23:55 UTC
Labels: bug
