### ISSUE TITLE
Feature Request: Room Map

### ISSUE THREAD

**Issue by pleg** [Hyrules/WinHue3#152] opened 2018-01-07 17:15 UTC
it would be really cool to select lights using a mini map. basically just a embed a picture from HDD that was created from another application (for example the OSS "Sweet Home 3D" application) and icons positioned overlay. ideally also with a rectangle selection tool.

**Comment by Hyrules** [comment] 2018-01-07 17:17
Interesting Idea. Never though of this don't know how hard it is to implement. I'll take a look.

**Comment by Hyrules** [comment] 2018-07-23 22:48
I currently implementing this functionnality to WinHue any special demand you would like or way of working worth mentionning  ?

**Comment by pleg** [comment] 2018-07-24 00:57
ok a few ideas, in no particular order:

- click to toggle lamp and click to toggle group.
- lasso, rectangle select and multiple selection (with checkbox or CTRL+click)
- just hover over the lamp icon and using the mouse wheel to control hue or brightness.
- the ability to filter the display of lamp icons on the map (show only group)
- some form of visualization that shows the shine/radius (this is graphics intense)
- drag and drop with other elements of the UI?!
- gestural control the way music software emulates physical knobs (click and hold then drag mouse to control knob level)

i'm just throwing ideas. maybe with .net libraries they aren't too hard to implement or maybe not

**Comment by pleg** [comment] 2018-07-24 01:05
![image](https://user-images.githubusercontent.com/13636838/43110771-1d56747e-8eee-11e8-8350-d189138d5a14.png)

this is my UI now, i would be happy to replace it

**Comment by Hyrules** [comment] 2018-07-24 10:33
Some of those are easy to implement others are more complex. for example the radius thing this might required some graphic intensive functionnalities. filtering on the other hand can be easy to do. I'll see what I can do.

**Comment by Hyrules** [comment] 2018-08-13 22:38
Right now I have something like this : 

![image](https://user-images.githubusercontent.com/3161577/44061845-02fed48c-9f28-11e8-8d36-1b4221a7c27b.png)

**Comment by banksio** [comment] 2018-08-13 22:53
Just a quick thought, it might be a good idea to have the size of the lights be adjustable? I'm thinking of the few edge cases where someone has loads of lights in a small area, the large hitboxes may not work in that case... But I'm not sure if that's easy or even possible to implement.

**Comment by Hyrules** [comment] 2018-08-13 23:01
already planned. I just don't have it implemented yet.

**Comment by Hyrules** [comment] 2018-09-21 15:31
This will be in the next version. I have almost finished implementing it at it seems to work as intended.

**Comment by Hyrules** [comment] 2018-10-06 16:55
Implemented in the latest version.

**Closed by Hyrules** 2018-10-06 16:55 UTC
Labels: feature request
