### ISSUE TITLE
RC3 crashes at startup

### ISSUE THREAD

**Issue by Craig-NZ** [Hyrules/WinHue3#108] opened 2017-08-27 19:09 UTC
When I first installed the program it worked okay.  I was able to pair the hue bridge
[WinHue3 2017-08-28.txt](https://github.com/Hyrules/WinHue3/files/1254649/WinHue3.2017-08-28.txt)
, but none of the menu items were available.  So I closed the program and restarted, now it crashes but the menu items are now available.  Maybe something in the hue bridge is causing the problem?

**Comment by Craig-NZ** [comment] 2017-08-27 19:10
Forgot to mention, this is after I uninstalled the old versions and installed the version recommended in my previous issue (which I closed).

**Comment by Hyrules** [comment] 2017-08-27 22:05
I will take a look. It seem that there is an error processing the sensors.

**Comment by Hyrules** [comment] 2017-08-27 22:16
ok got it. That a new one. There is a null error because the program does not recognize your sensor 9.  Which is a kind of sensor I never seen before.

**Comment by Craig-NZ** [comment] 2017-08-27 23:16
I'm not sure what a sensor 9 is .. maybe a new version of a light or switch.  I think there are only two component types on my system: bulb, dimmer switch.

**Comment by Craig-NZ** [comment] 2017-08-27 23:17
Also, it seemed to work okay with the beta version of the software I was running two days ago.

**Comment by Hyrules** [comment] 2017-08-27 23:18
I think it's a geofence. if you geofenced some light with the Philips Hue App or any other it might have created those sensors.

**Comment by Craig-NZ** [comment] 2017-08-28 00:19
The only change I can think of was installing a remote app on my Android phone that would let me setup timers on the lights.  This seemed to have caused some other changes, so when I get WinHue running I will use it to 'reset' everything.

**Comment by AZ-Geek** [comment] 2017-09-01 23:16
@Hyrules would it help for @Craig-NZ to: 
Close the WinHue app
Delete "C:\Users\%username%\AppData\Roaming\WinHue\WinHueSettings.set"
Open WinHue
Connect to Hue bridge

I'm using RC3 without issues

**Comment by Hyrules** [comment] 2017-09-01 23:40
Do you have a geofence sensor in your sensors ?

**Comment by Craig-NZ** [comment] 2017-09-02 00:11
Not that I am aware of.  Is there a way to check?  I am now running the
Beta v2.5 version of the software and it is working okay.  So something new
about v3.

Craig

**Comment by Hyrules** [comment] 2017-09-02 00:16
The problem is caused by a new sensor type I didn't account for that is why the program is crashing. Sorry @Craig-NZ I was asking to @AZ-Geek .

**Comment by AZ-Geek** [comment] 2017-09-02 13:16
@hyrules, no I have not enabled geofence on my Hue bridge.

**Comment by banksio** [comment] 2017-09-02 19:26
@AZ-Geek In that case you likely do not have the sensors in your system that are causing Craig-NZ's WinHue instance to crash.

**Comment by osugregor** [comment] 2017-09-05 12:13
The app also immediately crashed for me this morning (fresh/first install). 
I disabled the "Home & Away" Location Aware functionality within the iOS app, deleted my WinHue settings file and relaunched/paired my bridge. It worked fine afterwards.

**Comment by cu-massive** [comment] 2017-09-12 09:16
I have same problem. Using IFTTT for turning on/off at sunset/sunrise. Maybe that generates a "sensor" that's unknown....

**Comment by Nitzowsky** [comment] 2017-09-16 19:46
Have the same problem, but cant fix
here is the log
[WinHue3 2017-09-16.txt](https://github.com/Hyrules/WinHue3/files/1308613/WinHue3.2017-09-16.txt)

**Comment by Hyrules** [comment] 2017-09-17 13:59
All of the above seems to be related to the same thing. A sensor that cannot be deserializer. It's either I ignore all unknown sensor and don't display them or try to find a way to create a generic sensor.

**Comment by joergenrasdk** [comment] 2017-09-21 08:05
I have the same  problem, and here i the last entry in the log:[System.String,WinHue3.Philips_Hue.HueObjects.SensorObject.ISensor])","HResult":-2147467261,"Source":"WinHue3","WatsonBuckets":"AQAAAEMATABSADIAMAByADMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFcAaQBuAEgAdQBlADMALgBlAHgAZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUAOQA4AGQAZgAwADgAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFcAaQBuAEgAdQBlADMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUAOQA4AGQAZgAwADgAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgANQA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIAYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFMAeQBzAHQAZQBtAC4ATgB1AGwAbABSAGUAZgBlAHIAZQBuAGMAZQBFAHgAYwBlAHAAdABpAG8AbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}

**Comment by joergenrasdk** [comment] 2017-09-21 08:13
Here is my complete config file from Hue API. 
[HueConfig-20170921.txt](https://github.com/Hyrules/WinHue3/files/1320402/HueConfig-20170921.txt)

**Comment by Hyrules** [comment] 2017-09-22 21:12
Some of you mentionned IFTTT can anyone tell me which recipe in particular that generate a sensor I will try to find what is the sensor causing this.

**Comment by banksio** [comment] 2017-09-23 10:50
@Hyrules I don't think IFTTT creates any sensors. It's just a direct command. I use it with my Google Home and no issues there. I may be wrong though.

**Comment by Hyrules** [comment] 2017-09-23 15:33
Roger that anyhow I think I have a solution for sensors. I just discovered a new dynamic object in c# called ExpandoObject that might do the trick.

**Comment by banksio** [comment] 2017-09-24 10:04
@Hyrules That's good, hopefully it will work and end these sensor shenanigans!

**Comment by BVMiko** [comment] 2017-09-29 00:28
I was also experiencing a NullReferenceException on launch caused by an invalid sensor.  WinHue had been working fine, and I had a new sensor configuration window open.  I had another window opened (searching the internet for custom sensor integrations), and I suspect I may've accidentally saved an invalid sensor to my hue bridge.

From the Hue Android app's settings tab I was able to select my bridge and perform a "Clean up", which removes various things, including the invalid sensor.  It also claims that it will restore the lights and rooms afterwards; however I'd already removed them manually.

Just throwing that out there as a potential workaround for others in a similar situation.

**Comment by Hyrules** [comment] 2017-10-07 15:49
Anyone interested in testing RC3 and let me know if there are any issues I havn't found ?

[WinHue 3 RC 3 - 3.0.115.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1366219/WinHue.3.RC.3.-.3.0.115.0.Setup.zip)

**Comment by joergenrasdk** [comment] 2017-10-08 15:09
Yes - it still crashes at startup on my computer

**Comment by Hyrules** [comment] 2017-10-08 15:51
Ok I think I know why some of you crash at startup. If you don't update your bridge this will happen because some properties does not exists anymore in the old versions of the bridge like the schedule localtime property that exists in the new version but not in the old version. When using WinHue you always should have the latest version of the bridge otherwise this will happen. @joergenrasdk this is a problem in your case. Try updating the bridge to the latest version this will go away.

**Comment by banksio** [comment] 2017-10-08 16:44
@Hyrules Maybe you could add a MsgBox that prompts for this at startup if the verison is too old.

**Comment by Hyrules** [comment] 2017-10-08 17:18
I have disable everything. Especially the deserialization because that's where it crashes. I will enable only the update button.

**Comment by Hyrules** [comment] 2017-10-09 01:07
Here is a tentative version for RC3. Anybody willing to test it ? The only thing I have not tested is crashing when loosing connection. I will do that tomorrow. Otherwise you can test it.

[WinHue 3 RC 3 - 3.0.240.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1367339/WinHue.3.RC.3.-.3.0.240.0.Setup.zip)

**Comment by banksio** [comment] 2017-10-09 08:21
@Hyrules I'll be able to test it later today, will report back.

**Comment by Hyrules** [comment] 2017-10-09 13:37
I know there is an exception when creating hotkeys by selecting a scene. I will correct it.

**Comment by banksio** [comment] 2017-10-09 20:56
Nothing I can find that crashes it, besides what you've already mentioned. But I realised I'm not the OP who had issues, so unfortunately I can't give a full report!

**Comment by Hyrules** [comment] 2017-10-09 21:03
No problem. Let's wait for the others to test this version. Anyway If you pull the latest dev version you will see that i'm further ahead of this release and I have fixed and implemented more stuff. I have a few more thing I want to do before release RC3. I have done a massive cleanup of the dev source files removing most of the unused code and leftovers from previous version. Added some dependencies.

**Comment by banksio** [comment] 2017-10-09 21:07
Funnily enough I have actually just pulled the latest dev, I can see you've made loads of commits. Always good to do a cleanup. Quick note though: all my settings seem to have been reset and now it can't find my bridge.

**Comment by Hyrules** [comment] 2017-10-09 21:10
well yes that intented unfortunately. I have splited the settings in 3 files. Hotkeys, Bridges and App settings. Since your settings are in the App settings the app does not get the info from there anymore so a re-pairing is required to make the application work. This also applies to hotkeys.

**Comment by banksio** [comment] 2017-10-09 21:17
Ah, I see. Yeah, it works fine after re-pairing. I noticed you put my name in the readme by the way, thank you!

**Comment by D1311** [comment] 2017-10-10 01:27
Sorry but an unexpected exception occured. Please report the exception on the suport website (you know how it goes.) When I click OK, WinHue has stoppedworking.

Forgot to mention I already done rc3 as rc2 was the smae and I thought the new one would work. 
Gonna try that  re-pairing, see if that works. Nope that didn't help.

**Comment by Hyrules** [comment] 2017-10-10 01:36
Ill need a log to see what happens.

**Comment by D1311** [comment] 2017-10-10 01:54
I have no idea if this has worked if not could you do a step by step.

**Comment by Hyrules** [comment] 2017-10-10 02:03
Does not seem to have can you attach the whole log with the crash here I'll take a look at it tomorrow.

**Comment by D1311** [comment] 2017-10-10 02:05
I thought thats what I did, If not I have no Idea how to do it. does pic
mean anything

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Hyrules** [comment] 2017-10-10 02:15
Don't reply using email. Github seems to filter all attchments added to the mail you will need to use the web page.

**Comment by D1311** [comment] 2017-10-10 09:44
![capture](https://user-images.githubusercontent.com/28877894/31379992-e567e48a-ada7-11e7-86cf-73c91cbf9c19.PNG)
I have no idea what I doing, but I hope this helps. Hope it's the right part.

**Comment by Hyrules** [comment] 2017-10-10 10:28
No i really need the log file. Even if you send me a picture it wont help I need to cut and paste your settings in my debugger so I can see what happens. the log file is located in your appdata folder ( %appdata% type this in Windows explorer bar ) Thanks.

**Comment by D1311** [comment] 2017-10-10 11:05
Not sure which one it is so I'll send 2.

[6th](https://pastebin.com/EvdnJmUp)

[9th (too large for Pastebin)](https://file.io/SjUUBx)

**Comment by D1311** [comment] 2017-10-10 11:41
see if this works
[WinHue3 2017-10-09.txt](https://github.com/Hyrules/WinHue3/files/1371714/WinHue3.2017-10-09.txt)

**Comment by Hyrules** [comment] 2017-10-10 12:09
This should do. I will take a look at it after work today.

**Comment by Hyrules** [comment] 2017-10-10 20:14
Good news it that it's not the serialization. Can you tell me the settings you used when creating a schedule that crashes ?

**Comment by D1311** [comment] 2017-10-10 20:45
Anything to do with timers/scheds and alarms,

**Comment by D1311** [comment] 2017-10-10 20:50
I pick a time/date click OK and crash. Just tried it again (rc3).

**Comment by D1311** [comment] 2017-10-10 20:51
Plus I keep getting update is available do you want to update I click Yes and nothing happens.

**Comment by D1311** [comment] 2017-10-10 20:55
![capture 1](https://user-images.githubusercontent.com/28877894/31410015-aa712608-ae05-11e7-87b2-8fc86824ceb2.PNG)
![capture2](https://user-images.githubusercontent.com/28877894/31410016-aa9bdee8-ae05-11e7-8a91-18d469ff82d6.PNG)
![capture3](https://user-images.githubusercontent.com/28877894/31410018-aacd6990-ae05-11e7-8123-fb154a9c98ba.PNG)
![capture4](https://user-images.githubusercontent.com/28877894/31410019-ab20b816-ae05-11e7-9b51-78f8430ced8e.PNG)
Unless you mean these settings

**Comment by Hyrules** [comment] 2017-10-10 20:58
This should fix the crash in the schedule. For the update i'm looking at it right now.
[WinHue 3 RC 3 - 3.0.290.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1373419/WinHue.3.RC.3.-.3.0.290.0.Setup.zip)

**Comment by D1311** [comment] 2017-10-10 21:15
![capture5](https://user-images.githubusercontent.com/28877894/31411070-61ebc8ae-ae08-11e7-84ee-03539a8d3797.PNG)
Nothing there now, can't click on any thing except the top folders.

**Comment by Hyrules** [comment] 2017-10-10 21:17
I'll need an event log.

**Comment by D1311** [comment] 2017-10-10 21:19
[WinHue3 2017-10-10.txt](https://github.com/Hyrules/WinHue3/files/1373458/WinHue3.2017-10-10.txt)

**Comment by Hyrules** [comment] 2017-10-10 21:20
Do you try closing the app and reopening. I know there is a bug after pairing a bridge that the screen stays white.

**Comment by D1311** [comment] 2017-10-10 21:21
doing it now

**Comment by D1311** [comment] 2017-10-10 21:22
working, thanks

**Comment by D1311** [comment] 2017-10-10 21:23
I mean all there and tried a scged works no crash.

**Comment by Hyrules** [comment] 2017-10-10 21:24
ok so i'll fix the white screen bug next and if you still have the update message you can fix this temporarily but going in the settings of the app and unchecking the Check for WinHue update at startup.

**Comment by D1311** [comment] 2017-10-10 21:25
K, thanks

**Comment by Hyrules** [comment] 2017-10-10 23:00
Here is another version for you guys to test. This one is really close to the next release. Only one issue i'm aware that I will try to fix tomorrow.

[WinHue 3 RC 3 - 3.0.298.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1373674/WinHue.3.RC.3.-.3.0.298.0.Setup.zip)

**Comment by D1311** [comment] 2017-10-10 23:40
No white screen, and scheds work.

**Comment by Nitzowsky** [comment] 2017-10-12 16:11
Now its working here

**Comment by joergenrasdk** [comment] 2017-10-12 19:26
3.0.298.0 do not crash at startup - so from my point of view the issue is solved.

**Comment by Hyrules** [comment] 2017-10-12 21:42
glad to hear that the issue seems to be fixed. Although i'm not ready to call this version the magic version because there are still some issues that I need to fix before a release. For example if you try to create a rule you wont be able to select a sensor state sub property. This problem is particularly complex because I use reflexion of the main object and I get an interface type instead of a actual object type. So you will not see the properties of a sensor state or config at the moment. This is not an easy problem to fix.

**Comment by D1311** [comment] 2017-10-15 22:23
Had a crash trying to update the Iris to an earlier time.
[WinHue3 2017-10-15.txt](https://github.com/Hyrules/WinHue3/files/1385878/WinHue3.2017-10-15.txt)

**Comment by Hyrules** [comment] 2017-10-15 23:42
I don't understand what you mean by update the iris to an earlier time... I see the crash but your datastore deserialize without problem here.

**Comment by D1311** [comment] 2017-10-16 02:17
I go into schedules then edit (this time lamp 1) and when I change the time, crash. (same message I was getting before)

**Comment by Hyrules** [comment] 2017-10-16 10:39
Yeah ok I see why. You used a random time to set the lamp on so there is an A character in the lamp 1 off scene time when you edit it I will fix this.

**Comment by Hyrules** [comment] 2017-10-21 15:36
RC3 Released closing this as this has been fixed. Please create other issues if you still have any problem.

**Closed by Hyrules** 2017-10-21 15:36 UTC
Labels: bug
