### ISSUE TITLE
colour loop flash

### ISSUE THREAD

**Issue by D1311** [Hyrules/WinHue3#127] opened 2017-11-07 17:23 UTC
When on dim (when you really notice it) as it goes to a new colour it flashes bright for split second. At first I thought it was the one bulb but it does it with all on dim.
[WinHue3 2017-11-07.txt](https://github.com/Hyrules/WinHue3/files/1450975/WinHue3.2017-11-07.txt)

P.s. I also tryed turning the update off but it keeps turning itself back on, or it doesn't turn off.

**Comment by Hyrules** [comment] 2017-11-07 22:09
I'm unable to reproduce that bug here. When I'm dimmed I click on color loop it just goes to color loop mode and start looping. After looking at the code it cannot do that. All I do is create an empty object and put effect = colorloop. there is not brightness sent to the bridge at the same time. After looking at your log I also cannot find anything suspicious. The command is properly sent to the bridge. It would show in the bridge reply if the app would have send a bri setting with the color effect : 

2017-11-07 17:12:04,488 [1] DEBUG WinHue3.Philips_Hue.Communication.Serializer [DeserializeToObject:67] ==> [{"success":{"/lights/5/state/effect":"colorloop"}}]

Success would tell me that I had sent the bridge. I don't have version 1.20 of the bridge since i'm still using an old bridge it might be related I don't know. 

For the app update as stated in the log it's normal. The app will try to check even if you don't want it. It just won't prompt you to update if there is any.

**Comment by banksio** [comment] 2017-11-09 21:32
@D1311 Does it do it with all of the bulbs you have? I am just thinking of options here as I have a newer bridge and no issues. May be a hardware issue?

**Comment by D1311** [comment] 2017-11-09 21:59
I only have 3 colour bulbs and it does it on all 3. Just tried the 2 living lights and they seem to flash but the iris seems smooth.

**Comment by Hyrules** [comment] 2017-11-09 22:01
I think I saw somewhere on the philips forums that there were people having this issue but i'm not sure. I know there was an issue with the preview function at some point where it was exhibiting what you are talking about but it was specific to preview. I have done a debug of the application step by step and it does not send any brightness command to the bridge. Do you have this issue if you use the philips hue app or any other app ? i'm trying to find if this indeed related to WinHue because with software engineering an issue can happen somewhere and not at another place.

**Comment by D1311** [comment] 2017-11-09 22:10
Son has all4hue as well and just did the dim and it flashes with that

**Comment by banksio** [comment] 2017-11-09 22:12
Might be sounding a little stupid here, but are they connected at all to dimmer switches? This is a common issue with them, even if they are turned up fully.

**Comment by D1311** [comment] 2017-11-09 22:12
no

**Comment by banksio** [comment] 2017-11-09 22:13
Hmm. Have you tried other sockets? If yes then I'm out of ideas!

**Comment by D1311** [comment] 2017-11-09 22:17
Just tried it without dim full sat and full temp and it really only does it as it goes from light blue to pink.

Sockets? it is in a multi plug socket.

**Comment by D1311** [comment] 2017-11-09 22:20
I'll have to try another day, too much stuff to move and nearly bedtime.

Thanks

**Comment by Hyrules** [comment] 2017-11-10 11:38
if this happens with other applications there is either a rule affecting the lights or some defective hardware.

**Comment by Hyrules** [comment] 2017-12-24 15:28
did you found out what caused this issue ?

**Comment by D1311** [comment] 2017-12-24 20:37
Haven't noticed it, so that's good.

**Comment by Hyrules** [comment] 2017-12-24 20:39
great so i'll close this issue if there is something else dont hesitate.

**Closed by Hyrules** 2017-12-24 20:39 UTC

**Comment by D1311** [comment] 2017-12-24 21:15
K, Thanks again.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
