### ISSUE TITLE
RC2 crashes when Advanced Creator is clicked

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue3#106] opened 2017-08-25 21:16 UTC
As the title says, whenever I click the _Advanced Creator_ button in the ribbon, the app throws an exception and crashes. [Here's the log](https://pastebin.com/f5cwZbLq).

**Comment by Hyrules** [comment] 2017-08-25 22:44
Ok this one is easy. I forgot to add the the dll for the editor.

**Comment by Hyrules** [comment] 2017-08-25 23:52
you can try the version in #105 it should fix this issue but not the other you reported.

**Comment by banksio** [comment] 2017-08-25 23:56
Yup, works great. Thanks!

**Comment by banksio** [comment] 2017-08-26 00:03
New issue, when clicking Clear in the ribbon in the Advanced Creator, the app crashes. [Here's the log](https://pastebin.com/T5mkdR2Y).

**Comment by Hyrules** [comment] 2017-08-26 00:06
hmmm the error is cryptic really. It does not mean anything. Does this happen everytime or only in certain condition ?

**Comment by banksio** [comment] 2017-08-26 00:16
It is quite strange, the error only occurs if the text blinking cursor is anywhere other than before the first character. So if the cursor is here `|{"na...` it will not crash but if the text cursor is anywhere else, for example here `{"|na...`, it will crash.

**Comment by Hyrules** [comment] 2017-08-26 00:17
ok got it I can reproduce. I know where and why this happens...

**Comment by Hyrules** [comment] 2017-08-26 00:25
Here you go.

[WinHue 3 RC 3 Setup.zip](https://github.com/Hyrules/WinHue3/files/1253273/WinHue.3.RC.3.Setup.zip)

**Comment by banksio** [comment] 2017-08-26 00:28
Yep, works flawlessly now. Thanks! Anything else I find I'll be sure to post.

**Comment by Hyrules** [comment] 2017-10-10 22:46
Closing this since it is fixed. I'll upload RC3 soon.

**Closed by Hyrules** 2017-10-10 22:46 UTC
Labels: bug
