### ISSUE TITLE
Settings not loaded

### ISSUE THREAD

**Issue by GrimDeclaw** [Hyrules/WinHue3#137] opened 2017-12-13 13:53 UTC
Hi,

First : thanks for this software, which is more than usefull when you want to get your hands "dirty" and setup some "fancy" stuff within the hue bridge!

My issue is that since RC3 the settings (anything set in the "WinHue 3 Settings...") are not loaded at startup.
I'd like to change the langage to "French" in "Main settings" and "Show ID" in "View Settings".
While "Show ID" work without a restart, it's kind of fine (while annoying) but language which require a restart can't be set at all.
I checked the WinHueSettings.set and while it's been written accordingly, those settings are not loaded at startup. I tried deleting WinHueSettings.set and it's been recreated by the software with default values, but still when I change something it isn't reflected on restart (while the file is)

Nothing wrong in the log file:
2017-12-13 14:40:11,759 [1] DEBUG WinHue3.Functions.Application_Settings.Settings.WinHueSettings [LoadBridges:174] ==> Loading bridge settings : {
  "BridgeInfo": {
    "XX:XX:XX:XX:XX:XX": {
      "ip": "XXXXXXXX",
      "apikey": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
      "apiversion": "1.22.0"
    }
  },
  "DefaultBridge": "XX:XX:XX:XX:XX:XX"
}
2017-12-13 14:40:11,759 [1] DEBUG WinHue3.Functions.Application_Settings.Settings.WinHueSettings [LoadBridges:176] ==> Deserializing the settings file.
2017-12-13 14:40:12,687 [1] INFO  WinHue3.Utils.UpdateManager [CheckForWinHueUpdate:37] ==> Checking for WinHue 3 update...
2017-12-13 14:40:12,922 [1] INFO  WinHue3.MainForm.MainFormViewModel [LoadBridges:117] ==> Loading bridge(s)...
2017-12-13 14:40:12,923 [1] INFO  WinHue3.MainForm.MainFormViewModel [LoadBridges:119] ==> Checking if any bridge already present in settings... found 1
2017-12-13 14:40:12,923 [1] INFO  WinHue3.MainForm.MainFormViewModel [LoadBridges:132] ==> Bridge OK. Checking if bridge already in the bridge list...
2017-12-13 14:40:12,925 [1] INFO  WinHue3.MainForm.MainFormViewModel [LoadBridges:150] ==> Bridge not in the list adding it... 

I also tried the RC4 WinHue 3 RC 4 - 3.0.927.0 Setup.zip (from the hotkey issue) but still.

Thanks again, if you need a full log file, I can provide it (after I redacted some MAC/IP and stuff like that from it!)

**Comment by Hyrules** [comment] 2017-12-13 13:54
Most likely there won't be any error in the log for this if there is a missing piece of code. I will try to take a look at this and have it fixed for the next version.

**Comment by GrimDeclaw** [comment] 2017-12-13 14:00
Thanks, not really a big need, as I seems to be the only one noticing it and while it's annoying it's not preventing me from using it (I can cope with English language ;) ) and I'm pretty sure you have more important stuff to take care off. This was just FYI ;)

**Comment by Hyrules** [comment] 2017-12-13 14:01
Pas de problème. Je vais corriger ce bug sous peu. Merci ;)

**Comment by Hyrules** [comment] 2017-12-14 00:25
This version should work properly. There was an error in the installer actually. File where not installed at the right place.

[WinHue 3 RC 4 - 3.0.992.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1557556/WinHue.3.RC.4.-.3.0.992.0.Setup.zip)

**Comment by Hyrules** [comment] 2017-12-14 00:38
Hmmm might crash i think i forgot to add some referencies.

**Comment by GrimDeclaw** [comment] 2017-12-14 00:42
Well, it doesn't crash, but still not loading settings (deleted my WinHueSettings.set files again to be sure).
BTW, what do you mean by "File where not installed at the right place", because I installed WinHue on my E: drive, not C:
Might it be the problem? Or is it the "WinHueSettings.set" that is not search at the right place? (mine is in %appData\WinHue% (ie C:\users\Username\AppData\Roaming\WinHue\)

**Comment by Hyrules** [comment] 2017-12-14 00:46
There should be a fr and en folder in winhue install folder with the missing ressources missing now. Not the appdata folder.

**Comment by GrimDeclaw** [comment] 2017-12-14 00:50
Ok.
In "en" I have 1 file : System.Windows.Interactivity.resources.dll
In "fr" I have 3 files : System.Windows.Interactivity.resources.dll, WinHue3.resources.dll and Xceed.Wpf.AvalonDock.resources.dll

Still same issue : Settings are not loaded

Once again : this is not critical, don't waste too much time on it, you'll figure it out when you'll figure it out, no rush ;)

**Comment by Hyrules** [comment] 2017-12-14 11:33
that's odd. I was able to reproduce the bug here as well but now it seems to be fixed on my side. I can change the language if you have both folder it should work. The files you have in those folder are about right.

**Comment by GrimDeclaw** [comment] 2017-12-14 11:37
I'll try a full uninstall/redownload/reinstall and let you know

**Comment by Hyrules** [comment] 2017-12-14 11:41
Also try to delete your settings file for the app. You do not need to delete the pairing and hotkeys file.

**Comment by GrimDeclaw** [comment] 2017-12-14 11:41
Nop. Still no luck.
Uninstalled, delete the %appData%/WinHue folder, reinstall ... and same. My Settings are well saved in the WinHueSettings.set, but not loaded at launch

**Comment by GrimDeclaw** [comment] 2017-12-14 12:02
I tried the WinHue 3 RC 4 - 3.0.992.0 Setup.zip version on another computer (which never had WinHue installed before) and same result : settings are not loaded (my main computer has Win7, this one has Win10 FYI)

**Comment by GrimDeclaw** [comment] 2017-12-14 12:30
Don't know if it is usefull, but whatever settings "Language" (even if I edit it manually to "xx-XX") in the WinHueSettings.set file is set, the log always show this line at startup :

2017-12-14 13:26:03,129 [1] DEBUG WinHue3.Functions.Application_Settings.Settings.WinHueSettings [LoadBridges:176] ==> Deserializing the settings file.
2017-12-14 13:26:03,274 [1] INFO  WinHue3.App [.ctor:41] ==> en-US

**Comment by Hyrules** [comment] 2017-12-14 12:40
yeah. I added a logging for the system language. As you see the locale does not seem to load for some reason.

**Comment by GrimDeclaw** [comment] 2017-12-14 12:43
Well, it might just be me (something on my computers). Don't waste any more time on this, it doesn't prevent me from using it.
Thanks again for your time, and all your work on WinHue!

**Comment by Hyrules** [comment] 2017-12-14 13:30
Still if you want I can try to fix this because if you have this bug chances are other have. If this is really a bug I want to fix it that's sure. This is not a waste of time for sure.

**Comment by GrimDeclaw** [comment] 2017-12-14 13:32
Not a big priority, let's wait and see if others report this kind of issue. 
If not, chances are great that this is only on my side!
Again: thanks!

**Comment by GrimDeclaw** [comment] 2017-12-14 13:46
Just one last question : If I want to try to look into this myself (never do C# but still ^^), which branch should I clone?

**Comment by Hyrules** [comment] 2017-12-14 14:38
If you want to be up to date clone the dev branch. Most of the time it should compile. Sometime the master branch can be far behind the dev. I only merge when I release a version.

**Comment by GrimDeclaw** [comment] 2017-12-14 17:26
Found it!
I don't have any hotkeys defined, so the LoadAllSettings() function, from Settings/WinHueSettings.cs load the bridge settings, try to load the hotkeys and return false, without trying to load settings.

public static bool LoadAllSettings()
        {
            if (LoadBridges() && LoadHotkeys() && LoadSettings()) return true;
            return false;
        }

If I invert LoadHotkeys() and LoadSettings() like this it works:
public static bool LoadAllSettings()
        {
            if (LoadBridges() && LoadSettings() && LoadHotkeys()) return true;
            return false;
        }

**Comment by GrimDeclaw** [comment] 2017-12-14 17:27
I confirm that creating a hotkey resolve the issue ;) (tried on the WinHue 3 RC 4 - 3.0.992.0 Setup.zip version)

**Comment by GrimDeclaw** [comment] 2017-12-14 17:31
To be more specific, my WinHueHotkeys.set is nearly empty : 
{
  "listHotKeys": []
}

This is enough for the settings to load

**Comment by Hyrules** [comment] 2017-12-14 19:18
Thanks. I will correct that tonight.

**Comment by GrimDeclaw** [comment] 2017-12-14 19:24
Glad I could help

**Comment by Hyrules** [comment] 2017-12-14 19:31
Technically speaking inverting both should not do anything more. 1 & 0 & 1 = 0 same as 1 & 1 & 0 = 0.
With an and if there is a zero anywhere it always result as zero but you are right in creating the empty file will result in a 1 because all are 1.

**Comment by GrimDeclaw** [comment] 2017-12-14 19:36
Except that if the code doesn't bother to launch the third test. 1 & 0 = 0 and whatever & comming after won't change anything, it is not even executed, so the settings are not loaded.

**Comment by Hyrules** [comment] 2017-12-14 19:38
hmmm i'll change that logic.

**Comment by GrimDeclaw** [comment] 2017-12-14 19:42
I found it suprising too, but my first test was on my laptop within Visual Studio after inverting the test (without defining hotkey).
I later test on my desktop with an empty hotkey file for passing the second test, and it worked.

As far as I can see, you have 2 options here : invert the logic (as Bridge and Settings files should always exists, but hotkey aren't mendatory) or create an empty hotkey set if it doesn't exists. Both choice should work ;)

**Comment by Hyrules** [comment] 2017-12-14 20:13
The odd thing is you would think that doing the old code was doing exactly that. But like you said it seem that when there is a false the rest of the functions is not executed. Well congrats you now know how to code in C# ;)

**Comment by GrimDeclaw** [comment] 2017-12-14 20:15
I wouldn't go that far ;)
But glad we can figure out this tricky one!

**Closed** 2017-12-24 15:28 UTC
Labels: bug
