### ISSUE TITLE
Adding lights to a group throws error

### ISSUE THREAD

**Issue by LordUsagi** [Hyrules/WinHue3#42] opened 2016-12-02 03:40 UTC
Sorry but an unexpected occurred. Please report the exception on the support website so the developer can fix the issues. Please include the most recent log located in the logs folder.

Here is the most recent log:

**Comment by Hyrules** [comment] 2016-12-02 11:37
Cannot reproduce the problem what are the steps you took to make this bug happen ?

**Comment by LordUsagi** [comment] 2016-12-03 04:38
Fresh install of WinHue Beta 23. 
Launch WinHue.
Create a group.
Select any bulb.
Add a name, or don't. Doesn't matter.
Click "Create" and boom an error and the app crashes.

**Comment by Hyrules** [comment] 2016-12-03 15:13
I still cannot reproduce the error. Can you give me your bridge API version it's located in the Bridge Settings button under the General Settings. You should be at 1.15.0 if it's not the case you need to upgrade your bridge firmware. That might be the cause of the exception. I'll have to dig more.

**Comment by LordUsagi** [comment] 2016-12-03 15:27
I can confirm I'm at 1.15.0. I'm also running Windows 7. It looks like I have .NET 4.6.1. I've tried running as administrator, running in compatibility. Reinstalling. Nothing seems to be working.

I can generate logs every time, so if you needed anymore, just lemme know!

**Comment by Hyrules** [comment] 2016-12-03 15:50
No problem. I'm looking into this right now. I have added some kind of failsafe but i don't understand why your get an null object.

**Comment by Hyrules** [comment] 2016-12-03 17:58
Can you try this version and send me the log file after you create a group. I want to see what happens. I have added some logging. It will not fix the problem. Might give you another error instead of an exception.
[Uploading WinHue 3 BETA 24 Setup.zip…]()

**Comment by LordUsagi** [comment] 2016-12-03 20:50
[log 2016-12-03.txt](https://github.com/Hyrules/WinHue3/files/629124/log.2016-12-03.txt)
Thanks for the assistance.

**Comment by Hyrules** [comment] 2016-12-03 21:28
ok this gives me more clues on what is null... now why... Try this version : 

[WinHue 3 BETA 24 Setup.zip](https://github.com/Hyrules/WinHue3/files/629134/WinHue.3.BETA.24.Setup.zip)

**Comment by LordUsagi** [comment] 2016-12-03 21:30
[log 2016-12-03 (2).txt](https://github.com/Hyrules/WinHue3/files/629135/log.2016-12-03.2.txt)

**Comment by Hyrules** [comment] 2016-12-03 21:33
I know why you have the error. As for why this variable is null god know... and this one ?
[WinHue 3 BETA 24 Setup.zip](https://github.com/Hyrules/WinHue3/files/629138/WinHue.3.BETA.24.Setup.zip)

**Comment by Hyrules** [comment] 2016-12-03 21:34
Can you also send me a screenshot of your WinHue window ? I want to check if I see anything suspicious.

**Comment by LordUsagi** [comment] 2016-12-03 21:34
![image](https://cloud.githubusercontent.com/assets/2440017/20862366/c41955e8-b97e-11e6-932a-ccbb1d79d0be.png)
I have no error after the latest install.

**Comment by LordUsagi** [comment] 2016-12-03 21:35
HueLib2 unknown error seems to pop up a lot, at the bottom or in the log files.

**Comment by Hyrules** [comment] 2016-12-03 21:36
Gees know I know why. This is not normal. You shouldn't have a blank Window at all. There should be at least some Lights and default groups and sensors. Did you pair your bridge with WinHue ?

**Comment by Hyrules** [comment] 2016-12-03 21:40
definitely something odd... I'm looking at the last log.

**Comment by LordUsagi** [comment] 2016-12-03 21:40
Yes I did. Is there a settings window you'd like to see of the two paired?

**Comment by Hyrules** [comment] 2016-12-03 21:42
Well there is the pairing windows but all I need is in the log. There seems to be a problem deserializing the Data store for the bridge. That is why the window is blank.

**Comment by Hyrules** [comment] 2016-12-03 21:47
try this in your browser and send me the result : http://192.168.2.12/api/nngyUe8GoLi8mIsh48U8agOEAEGVTSDhRaMYpxo9/

It will send me a full dump of your bridge. I suggest you put it in a text file.

**Comment by LordUsagi** [comment] 2016-12-03 21:49
[data.txt](https://github.com/Hyrules/WinHue3/files/629149/data.txt)

**Comment by Hyrules** [comment] 2016-12-03 22:02
Thanks I will try to debug with it. I'll see why it does not work.

**Comment by LordUsagi** [comment] 2016-12-03 22:03
Merci! Good luck!

**Comment by Hyrules** [comment] 2016-12-03 22:05
Speak french ? I'm from Quebec so oui merci :)

**Comment by LordUsagi** [comment] 2016-12-03 22:16
I am an Australian immigrant living in New Brunswick so I am forced to learn a little bit of french. Practice makes perfect

**Comment by Hyrules** [comment] 2016-12-03 22:17
Then Welcome to Canada / Bienvenue au Canada ! I hope I can find this bug for you soon so you can enjoy WinHue.

**Comment by Hyrules** [comment] 2016-12-03 22:39
I think I have it fixed : 
[WinHue 3 BETA 24 Setup.zip](https://github.com/Hyrules/WinHue3/files/629168/WinHue.3.BETA.24.Setup.zip)

**Comment by LordUsagi** [comment] 2016-12-03 22:50
WOAH. Look at all those new things that weren't there before. I'll keep this thread alive for a couple of days.

**Comment by Hyrules** [comment] 2016-12-03 22:50
Great ! Sure keep it there for a few. Nice to know it's now fixed.

**Comment by crypticedge** [comment] 2016-12-04 20:43
Popping in to say the beta 24 fixed the exact same issue for me

**Comment by LordUsagi** [comment] 2016-12-05 02:31
Couldn't find a way to contact you directly, but you don't have a couple of libraries included by default in the repo. Things like the UPnP handler etc. Any plans on adding those?

**Comment by Hyrules** [comment] 2016-12-05 17:40
You're right the package folder is not synched with the repo. I will add it later tonight.

**Comment by Hyrules** [comment] 2016-12-05 21:31
If you look at the dev branch there is now a package folder. Libraries should be in it.

**Comment by LordUsagi** [comment] 2016-12-05 23:02
Having some trouble specifically with AvalonEdit. How'd you get the project to recognize it?

**Comment by Hyrules** [comment] 2016-12-05 23:05
you have to add a reference to ICSharpCode.AvalonEdit.dll in WinHue.

**Comment by Hyrules** [comment] 2016-12-05 23:08
try nuget : https://www.nuget.org/packages/AvalonEdit

**Comment by LordUsagi** [comment] 2016-12-06 15:00
No such luck.

**Comment by frank-leitner** [comment] 2016-12-07 18:28
I pitch myself in as having the same issue.

Blank main screen of the program, HueLib2.UnknownError at the bottom, and crash on creating any group (the 'create a group' has all my lights available).

I just saw the Beta24 linked above and tried it out as well. Looks like it fixed the issue for me as well, a lot of things on the main screen now and just playing with a light or two worked.

**Closed** 2016-12-17 01:13 UTC
Labels: bug
